spring:
  data:
    # redis配置
    redis:
      # Redis数据库索引（默认为0）
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      # password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alhpa
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.daozhang.admin.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

sa-token:
  is-read-cookie: false
  token-prefix: Bearer
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
#  token-style: uuid
  # 是否输出操作日志
  is-log: false
  jwt-secret-key: shuaidediaozha
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
#    password:
    # 连接超时时间
    timeout: 10s

# 不要拿来直接用，需要自己去替换值
rsa:
  pubKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBTXSKQEHzxuTcWQwS6yGpGR9IMq7CH2UQ6vWz3iyaU8eAFlyApqkb8S5JzfRzTa53CIXu5OUPmUTSqyGCQFKmg8lplCpVK3fshYyPzS1lybfZbL0q20ztCTdkrbBSEYIPVluJqpyNysP8MOKLTvsMQoGSIavJIRfnlbEJUAyhZQIDAQAB
  priKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMFNdIpAQfPG5NxZDBLrIakZH0gyrsIfZRDq9bPeLJpTx4AWXICmqRvxLknN9HNNrncIhe7k5Q+ZRNKrIYJAUqaDyWmUKlUrd+yFjI/NLWXJt9lsvSrbTO0JN2StsFIRgg9WW4mqnI3Kw/ww4otO+wxCgZIhq8khF+eVsQlQDKFlAgMBAAECgYAfheGU8CCxQASveGgTJ7wgBuRGkllUd+kz5pU2BWvRqQr2NO9V3ZfjYiPxzj/ok8j5SW8KA9LlBdIm5th6lMHFdE/kfZUF6ZPaIQnxgvj779g59qgYh72gLgTw16KvQj/sJLS3zDXjG3QaDXPWiCICKiOHXb5h9yyD9S+uBWlOOwJBAOTfKEvTwVmNm1M6ms/OCY7uMM6OR6F/nigSwYCSeONAS/HauI3F3hOHmM4JCE3kbI/Dx+ntVY0jGj1FHVgzUOsCQQDYNv5uBCqghHaQ8hIw0vj+3WaU6W5HMzgPgG3wOhRrJ1JLXhvJ3DlUr/ZcnMpr5RHIqni13Rg4EnodeCs59sLvAkEAt6sCGn/vzR8fxBXmwNb2wrYRguGZSFgyorQSh0yEKNKjX46HxnZAtml9zfJfsKqcGG8kEm0814uQ9hRt7ScZSwJAEWISgJvbJX6g3bRom/5KQItiVPSThivrBOwJarfwrlDCAAc36rnG7jUbdISyjYwkKuLxw4VcDh4GLVpc91MMhwJBAOG2tF8dTL9IktueHg350XoSlyxGmVqztT3VPgfJ//w5n3Q538EU90R66OL99sCnTPytnC180yOAYpKruuMRhqo=
  enable: true

